"""SPEC-PARITY -- filler foreign locality knob (multiworld filler routing).

Controls how much of THIS slot's FILLER is allowed to travel to other players' worlds. Greenfield's
filler is the generic 'Rune' grant that every un-shuffled check pays out, plus -- when Shuffle
Vanilla Items is on -- the GOODS-nibble vanilla items core classifies as `filler` (consumables,
crafting mats, etc.). None of that is progression, so routing it never changes winnability.

Greenfield applies NO filler-locality control by default: filler can already land in any world (fully
open). This feature adds a single Range knob to pull some of it back home, mirroring the old apworld's
filler_foreign_pct but INVERTED to greenfield's model. The old world started from a fully-localized
filler set and carved `filler_foreign_pct`% back OUT of local_items (default 15 = keep 85% home).
Greenfield starts fully open, so here `filler_foreign_pct` directly names the share that MAY go
foreign: we force `(100 - pct)%` of the distinct filler item NAMES into `local_items`, leaving the
rest free to travel.

  * pct = 100 (DEFAULT) -> 0% localized -> NO CHANGE (current greenfield behavior: fully open).
  * pct = 0            -> 100% localized -> all filler stays in-world.
  * pct = 50           -> ~half the distinct filler names kept home, half free.

MECHANISM mirrors features/local_items.py: `local_items.value` is AP's mutable set[str]; we
`.update(...)` it in generate_early, and AP's `locality_rules(multiworld)` reads it fresh during fill
(players > 1) to forbid other worlds from holding those names. Solo seeds wipe local_items -> inert
(as intended). Composes with local_items (Local Items Only) since we only ADD names -- if that toggle
already localized everything, this is a further no-op.

Name-based (like the old world): the fraction is of the DISTINCT filler item NAMES, not per-item
copies. 'Rune' is the dominant filler and a single name, so with shuffle OFF the choice is coarse
(Rune is either home or free); with shuffle ON there are many distinct GOODS names to spread across.
Deterministic: the sample is drawn with world.random (seeded), never the global RNG.

Matt-free: filler names come from core's FILLER constant + the param-derived ITEM_CATALOG GOODS
nibble -- no curated/location data. slot_data: locality is enforced AP-server-side in fill, the client
never needs it -> {} (we still surface a tiny diag of how many names were localized).
"""
from typing import Any, Dict, List

from Options import Range
from ..registry import Feature, register

try:  # generated by gen_data.py (real-item-pool: {vanilla_item_name: ER FullID}); matt-free
    from ..item_ids import ITEM_CATALOG
except Exception:  # not yet generated -> only the generic Rune filler exists
    ITEM_CATALOG = {}

# The GOODS core promotes to `useful` -- they carry the goods nibble but are not filler, so they must
# not appear in this feature's filler list. Hand-owned taxonomy, safe for a feature to import.
from ..item_categories import USEFUL_GOODS as PROMOTED_GOODS

# core's generic filler item name + the GOODS high-nibble that core classifies as filler. Kept as
# local constants (importing core would cycle); these mirror core.FILLER / core._GOODS_NIBBLE.
FILLER_NAME = "Rune"
_GOODS_NIBBLE = 0x40000000

# pct that means "no change" (fully open == current greenfield behavior). Documented default.
NO_CHANGE_PCT = 100


def _shuffle_on(world) -> bool:
    sh = getattr(world.options, "item_shuffle", None)
    return bool(sh and sh.value)


def filler_names(world) -> List[str]:
    """Distinct filler item NAMES for this world, sorted (deterministic). Always includes the
    generic Rune; adds GOODS-nibble catalog items only when Shuffle Vanilla Items is on (they only
    exist in the pool then).

    🛑 MINUS THE PROMOTED GOODS. This reads the nibble, not the classification, and core promotes a
    short list of GOODS to `useful` (core._USEFUL_GOODS -- Golden Seed, Sacred Tear and the DLC
    ladders). Without this subtraction the two would disagree about the same item: a low
    filler_foreign_pct would localize a Golden Seed as "filler" while every other consumer treats it
    as useful, and the count this feature reports to the player would be counting the wrong pool."""
    names = {FILLER_NAME}
    if _shuffle_on(world):
        _excl = getattr(world, "gf_dlc_excluded", ())
        names.update(n for n, full in ITEM_CATALOG.items()
                     if (full & 0xF0000000) == _GOODS_NIBBLE
                     and n not in _excl and n not in PROMOTED_GOODS)
    return sorted(names)


class FillerForeignPct(Range):
    """Percent of THIS slot's filler (the generic Rune, plus vanilla GOODS when Shuffle Vanilla
    Items is on) that MAY travel to other players' worlds in a multiworld. 100 (default) = fully
    open, greenfield's current behavior (no change). Lower values keep more of your filler in your
    own world: at pct we force (100 - pct)% of the distinct filler item names local. 0 = keep all
    filler home. A propensity by distinct item name, not a hard per-copy rule. Inert in a solo seed
    (no other worlds) and composes with Local Items Only."""
    display_name = "Filler Open to Foreign (%)"
    range_start = 0
    range_end = 100
    default = 100  # NO_CHANGE_PCT: 100 -> localize 0% -> unchanged fully-open filler routing


@register
class FillerForeignFeature(Feature):
    name = "filler_foreign"
    OPTIONS = {"filler_foreign_pct": FillerForeignPct}

    # ---- helpers ------------------------------------------------------------------------------
    def _pct(self, world) -> int:
        opt = getattr(world.options, "filler_foreign_pct", None)
        return int(opt.value) if opt is not None else NO_CHANGE_PCT

    def names_to_localize(self, world) -> List[str]:
        """The distinct filler names this feature forces local for `world`. Empty at the default
        (pct 100 -> 0% local). Deterministic: chosen with world.random over the sorted name list."""
        pct = self._pct(world)
        if pct >= NO_CHANGE_PCT:
            return []  # fully open -> nothing localized (no change)
        names = filler_names(world)
        if not names:
            return []
        # (100 - pct)% of the distinct names, floor-rounded, kept home.
        k = (len(names) * (100 - pct)) // 100
        if k <= 0:
            return []
        if k >= len(names):
            return list(names)
        # deterministic sample from the seeded world RNG (never global random).
        return sorted(world.random.sample(names, k))

    # ---- hooks --------------------------------------------------------------------------------
    def generate_early(self, world) -> None:
        names = self.names_to_localize(world)
        if not names:
            return  # default / fully open -> leave local_items untouched
        # local_items.value is a plain mutable set[str]; add (never clear) so we compose with the
        # player's hand list and with Local Items Only. locality_rules reads it later in Main.py.
        world.options.local_items.value.update(names)

    def slot_data(self, world) -> Dict[str, Any]:
        # Locality is enforced AP-server-side during fill; the client never needs it. Surface a tiny
        # diag of how many distinct filler names were forced local.
        return {"filler_foreign_localized": len(self.names_to_localize(world))}
