"""share_useful_pct -- force a share of this slot's USEFUL items out into other players' worlds.

# The measurement this exists for

Elden Ring's `useful` tier never reaches a partner game, and until 2026-08-15 nobody knew why.
Instrumenting `Fill.remaining_fill` in a real 4-slot generation (2 Elden Ring + 2 Hollow Knight,
stock AP 0.6.7) gave the answer, and it is nothing to do with item rules, locality, exclusion or
reachability -- all four were checked and cleared:

    fill_restrictive('Progression')
      locations IN : p1 1508 (mean idx 1944) | p2 1993 (1969) | p3 202 (2024) | p4 202 (1769)
      locations OUT: p1 1490 (mean idx 1755) | p2 1969 (1779) | p3  94 (2806) | p4  82 (2716)
                                                              ^^^ earliest surviving HK slot: 1876
    remaining_fill('Remaining')
      locations 3635, itempool 3635 {filler 2162, useful 1473}
      first 1473 slots -- where the useful tier lands -- are {p1: 642, p2: 831}.  ZERO Hollow Knight.

AP's rest-fill concatenates `filleritempool + usefulitempool` and pops from the END, so the useful
tier claims the FIRST N slots of a shuffled location list. The progression fill runs first and eats
locations front-to-back; Hollow Knight is small and progression-DENSE (202 -> 94 slots survive),
Elden Ring is huge and progression-SPARSE (1508 -> 1490). So every surviving partner slot sits in the
tail of the list, past where the useful tier ever reaches. Elden Ring supplies ~87% of the free slots
and therefore absorbs 100% of its own useful items.

That is upstream shape, not a bug, and no item_rule of ours can move it: our locations being
ACCEPTABLE is exactly the problem. The one lever that works is the opposite of a bar -- AP's
`non_local_items`, which forbids a named item in its OWN world and so forces the fill to look past
Elden Ring entirely.

# Mechanism

Mirror image of features/filler_foreign, which pushes names INTO `local_items`. Here we push names
into `non_local_items`, which `worlds/generic/Rules.locality_rules` reads fresh during fill:

    non_local_items = multiworld.worlds[receiving_player].options.non_local_items.value
    if non_local_items:
        forbid(receiving_player, receiving_player, non_local_items)

Name-based, on the DISTINCT useful names, drawn with `world.random` so a seed reproduces -- the same
convention filler_foreign documents at length ("propensity by distinct item name, not a per-copy
rule").

# Guard rails

  * SOLO IS SAFE WITHOUT US. `Main.py` wipes both localities when `multiworld.players == 1`, so a
    solo seed cannot strand an item that has nowhere else to go. We still return early on the option
    being 0 so the default costs nothing at all.
  * `Main.py` also does `non_local_items -= local_items` and `-= local_early_items`, preferring
    local. So this composes with Local Items Only / Keep Local / Filler Open to Foreign rather than
    fighting them: a name held local wins, and this feature simply does not move it.
  * CAPACITY. Every forced-out name must fit in somebody else's world. The pct is over distinct
    NAMES, and the option's own text says to keep it modest; the fill still has the whole partner
    pool to work with and AP falls back to swapping.

Matt-free: names come from the param-derived ITEM_CATALOG classification, no curated or location
data. slot_data: locality is enforced AP-server-side during fill, the client never needs it -> {}.
"""
from typing import Any, Dict, List

from Options import Range
from ..registry import Feature, register
from ..item_categories import USEFUL_GOODS

try:  # generated by gen_data.py (real-item-pool: {vanilla_item_name: ER FullID}); matt-free
    from ..item_ids import ITEM_CATALOG
except Exception:  # not yet generated -> no real items exist -> feature is a no-op
    ITEM_CATALOG = {}

# Mirrors core's nibble rule. Importing core would cycle (features may never import ..core), so the
# constant is restated here exactly as features/filler_foreign restates it.
_GOODS_NIBBLE = 0x40000000


def _shuffle_on(world) -> bool:
    sh = getattr(world.options, "item_shuffle", None)
    return bool(sh and sh.value)


def useful_names(world) -> List[str]:
    """Distinct USEFUL item NAMES for this world, sorted (deterministic).

    Everything that is not a GOOD (weapons, armour, talismans, ashes of war), plus the goods core
    promotes (item_categories.USEFUL_GOODS -- Golden Seed, Sacred Tear, the DLC ladders). Empty when
    Shuffle Vanilla Items is off, because then the pool holds no real items to share."""
    if not _shuffle_on(world):
        return []
    _excl = getattr(world, "gf_dlc_excluded", ())
    names = {n for n, full in ITEM_CATALOG.items()
             if (full & 0xF0000000) != _GOODS_NIBBLE and n not in _excl}
    names.update(n for n in USEFUL_GOODS if n in ITEM_CATALOG and n not in _excl)
    return sorted(names)


class ShareUsefulPct(Range):
    """What share of your useful items -- weapons, armour, talismans, spells, ashes of war, Golden
    Seeds and Sacred Tears -- is forced OUT of your own world and into somebody else's.

    0 (default) forces nothing out. That does not mean nothing travels: your useful items are already
    free to land anywhere. It means Archipelago is free to leave them all at home, and in a seed
    where Elden Ring is much larger than its partners it will -- measured on a four-slot seed beside
    two Hollow Knight slots, 1,473 of 1,473 useful Elden Ring items stayed in Elden Ring worlds, none
    reached Hollow Knight, and the reason is pure arithmetic: Elden Ring supplies most of the free
    checks, so it absorbs most of the items. The bigger your world is relative to your partners', the
    more this knob is doing.

    At 20, about a fifth of your distinct useful item names may not be placed in your own world at
    all, so the fill has to find a partner check for them. Your partners open Elden Ring weapons and
    talismans instead of only Smithing Stones.

    A share of NAMES, not of copies: at 20 roughly one useful name in five is forced out, and every
    copy of that name goes with it.

    🛑 KEEP IT MODEST. Every forced-out name has to fit somewhere else, and a small partner world
    fills up. High values on a seed with one tiny partner make generation work hard and can push it
    to swap placements it would rather not. This never affects winnability -- Region Locks are the
    progression and this knob does not touch them.

    No effect in a solo seed, or with Shuffle Vanilla Items off (there are no real items to share).
    Items you have already held back with Local Items Only or Keep Local stay held back: Archipelago
    prefers local, so this only moves what is still free to move."""
    display_name = "Share Useful Items"
    range_start = 0
    range_end = 100
    default = 0


@register
class ShareUsefulFeature(Feature):
    name = "share_useful"
    OPTIONS = {"share_useful_pct": ShareUsefulPct}

    def _pct(self, world) -> int:
        o = getattr(world.options, "share_useful_pct", None)
        if o is None:
            return 0
        try:
            return max(0, min(100, int(o.value)))
        except (TypeError, ValueError):
            return 0

    def names_to_share(self, world) -> List[str]:
        """The distinct useful names forced out of this world, sorted.

        🛑 The rng is only touched when the option is ON. At the default this returns before any
        draw, so the seed's stream is byte-identical to a world without this feature (CLAUDE.md
        rule 6). The endpoints are exact by construction, and the rounding is half-up in integers for
        the same reason released_locks documents: Python's round() is banker's, so a 50% setting on a
        1-name pool would share NOTHING and read as the feature being broken."""
        pct = self._pct(world)
        if pct <= 0:
            return []
        names = useful_names(world)
        if not names:
            return []
        if pct >= 100:
            return names
        k = (len(names) * pct + 50) // 100
        if k <= 0:
            return []
        if k >= len(names):
            return names
        return sorted(world.random.sample(names, k))

    # ---- hooks --------------------------------------------------------------------------------
    def generate_early(self, world) -> None:
        names = self.names_to_share(world)
        if not names:
            return
        # non_local_items.value is a plain mutable set[str] (OptionSet.__init__ -> set(...)), and
        # Main.py reads it long after generate_early -- the same contract features/local_items relies
        # on for local_items. Only ADD, so a name the player listed by hand survives.
        world.options.non_local_items.value.update(names)
        import logging
        logging.getLogger("Greenfield").info(
            "[greenfield] share useful: %d of %d distinct useful item name(s) forced OUT of this "
            "world (share_useful_pct %d)", len(names), len(useful_names(world)), self._pct(world))

    def slot_data(self, world) -> Dict[str, Any]:
        # Locality is enforced AP-server-side during fill (worlds/generic/Rules.locality_rules).
        return {}
