"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Region bosses (method=boss_arena) -> greenfield ap-ids,
joined by event flag. Matt-free. Dungeon-sweep triggers need EMEVD enrichment (SPEC P3)."""
REGION_BOSSES = {
    'Abyssal': [
        (7770774, 510560, 'Remembrance of the Lord of Frenzied Flame'),
    ],
    'Ainsel River': [
        (7770756, 510080, 'Remembrance of the Naturalborn'),
    ],
    'Ancient Ruins': [
        (7770775, 510600, 'Remembrance of the Saint of the Bud'),
    ],
    'Ashen Capital': [
        (7770755, 510070, 'Remembrance of Hoarah Loux'),
        (7770764, 510230, 'Elden Remembrance'),
    ],
    'Belurat': [
        (7770768, 510400, 'Remembrance of the Dancing Lion'),
    ],
    'Caelid': [
        (7770002, 172, "Radahn's Great Rune"),
    ],
    'Cerulean': [
        (7770772, 510480, 'Remembrance of Putrescence'),
    ],
    'Deeproot Depths': [
        (7770758, 510110, 'Remembrance of the Lichdragon'),
    ],
    'Enir Ilim': [
        (7770770, 510430, 'Remembrance of a God and a Lord'),
    ],
    'Ensis': [
        (7770780, 510900, 'Remembrance of the Twin Moon Knight'),
    ],
    'Farum Azula': [
        (7770760, 510150, 'Remembrance of the Dragonlord'),
        (7770761, 510160, 'Remembrance of the Black Blade'),
    ],
    'Haligtree': [
        (7770006, 176, "Malenia's Great Rune"),
        (7773891, 15000850, "[Sorcery] Loretta's Mastery"),
    ],
    'Leyndell': [
        (7770754, 510040, 'Remembrance of the Omen King'),
    ],
    'Mohgwyn': [
        (7770005, 175, "Mohg's Great Rune"),
    ],
    'Mountaintops of the Giants': [
        (7770766, 510310, 'Remembrance of the Fire Giant'),
    ],
    'Mt. Gelmir': [
        (7770004, 174, "Rykard's Great Rune"),
        (7770763, 510220, 'Remembrance of the Blasphemous'),
    ],
    'Raya Lucaria Academy': [
        (7770007, 14000800, 'Remembrance of the Full Moon Queen'),
    ],
    'Scadu Altus': [
        (7770773, 510550, 'Remembrance of the Mother of Fingers'),
    ],
    'Shadow Keep': [
        (7770771, 510460, 'Remembrance of the Impaler'),
        (7770776, 510620, 'Remembrance of the Shadow Sunflower'),
        (7770778, 510640, 'Remembrance of the Wild Boar Rider'),
    ],
    'Siofra River': [
        (7770767, 510330, 'Remembrance of the Regal Ancestor'),
    ],
    'Stormveil': [
        (7770753, 510010, 'Remembrance of the Grafted'),
    ],
}

_GEN_STAMP = {'inputs_hash': 'sha256:e39be82bff579e8f63099ac8d5a030941f6e724683e521e4b14f900701f0944f', 'module': 'boss_data.py', 'body_sha256': 'sha256:19701b6467e1376fa7ac59c040cd7a4cb7dabd57175b4ef1a86ad3f7d7583078'}
