"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Region bosses (method=boss_arena) -> greenfield ap-ids,
joined by event flag. Matt-free. Dungeon-sweep triggers need EMEVD enrichment (SPEC P3)."""
REGION_BOSSES = {
    'Abyssal': [
        (7770674, 510560, 'Remembrance of the Lord of Frenzied Flame'),
    ],
    'Ainsel River': [
        (7770656, 510080, 'Remembrance of the Naturalborn'),
    ],
    'Ancient Ruins': [
        (7770675, 510600, 'Remembrance of the Saint of the Bud'),
    ],
    'Ashen Capital': [
        (7770655, 510070, 'Remembrance of Hoarah Loux'),
        (7770664, 510230, 'Elden Remembrance'),
    ],
    'Belurat': [
        (7770668, 510400, 'Remembrance of the Dancing Lion'),
    ],
    'Caelid': [
        (7770002, 172, "Radahn's Great Rune"),
    ],
    'Cerulean': [
        (7770672, 510480, 'Remembrance of Putrescence'),
    ],
    'Deeproot Depths': [
        (7770658, 510110, 'Remembrance of the Lichdragon'),
    ],
    'Enir Ilim': [
        (7770670, 510430, 'Remembrance of a God and a Lord'),
    ],
    'Ensis': [
        (7770680, 510900, 'Remembrance of the Twin Moon Knight'),
    ],
    'Farum Azula': [
        (7770660, 510150, 'Remembrance of the Dragonlord'),
        (7770661, 510160, 'Remembrance of the Black Blade'),
    ],
    'Haligtree': [
        (7770006, 176, "Malenia's Great Rune"),
        (7773790, 15000850, "[Sorcery] Loretta's Mastery"),
    ],
    'Leyndell': [
        (7770654, 510040, 'Remembrance of the Omen King'),
    ],
    'Mohgwyn': [
        (7770005, 175, "Mohg's Great Rune"),
    ],
    'Mountaintops of the Giants': [
        (7770666, 510310, 'Remembrance of the Fire Giant'),
    ],
    'Mt. Gelmir': [
        (7770004, 174, "Rykard's Great Rune"),
        (7770663, 510220, 'Remembrance of the Blasphemous'),
    ],
    'Raya Lucaria Academy': [
        (7770007, 14000800, 'Remembrance of the Full Moon Queen'),
    ],
    'Scadu Altus': [
        (7770673, 510550, 'Remembrance of the Mother of Fingers'),
    ],
    'Shadow Keep': [
        (7770671, 510460, 'Remembrance of the Impaler'),
        (7770676, 510620, 'Remembrance of the Shadow Sunflower'),
        (7770678, 510640, 'Remembrance of the Wild Boar Rider'),
    ],
    'Siofra River': [
        (7770667, 510330, 'Remembrance of the Regal Ancestor'),
    ],
    'Stormveil': [
        (7770653, 510010, 'Remembrance of the Grafted'),
    ],
}

_GEN_STAMP = {'inputs_hash': 'sha256:6e786569526a11b77a7e69cb6725a437e5be2879d6b128012334be2e8f468d4d', 'module': 'boss_data.py', 'body_sha256': 'sha256:c642c2c0462ce15d194dd382094dde322ba119925a6875d4d9e3e237ab1246cc'}
