"""AUTO-GENERATED by tools/datamine_enemy_names.py -- DO NOT EDIT (regenerate: python tools/datamine_enemy_names.py; --check is the drift gate).

The DISPLAY NAME of a spawnable character model, for the `spawn_traps` yaml option.

SOURCE = NpcParam.nameId -> NpcName.fmg.xml, plus tools/datamine_enemy_names.CURATED_NAMES.
Small on purpose: 35 of the 390 spawnable models carry a name here -- the ones the game
itself names, plus 4 this project had already published. Nothing else is invented. See
the tool's docstring for why, and for the most-rows/lowest-nameId pick rule.
"""
# chr_id -> display name
ENEMY_NAMES = {
    2010: 'Blaidd the Half-Wolf',  # fmg
    2030: 'Rennala, Queen of the Full Moon',  # fmg; name also on 2031 -- lowest id is canonical
    2031: 'Rennala, Queen of the Full Moon',  # fmg; name also on 2030 -- lowest id is canonical
    2050: 'Ranni the Witch',  # fmg
    2060: 'The Two Fingers',  # fmg
    2110: 'Gurranq, Beast Clergyman',  # fmg
    2120: 'Malenia (Phase 1)',  # curated
    2160: 'Finger Reader Crone',  # fmg
    2170: 'Finger Reader Enia',  # fmg
    2180: 'Melina',  # fmg
    2500: "Tanith's Knight",  # fmg
    3170: 'Latenna the Albinauric',  # fmg; name also on 6210 -- lowest id is canonical
    3200: 'Merchant Kalé',  # fmg
    3320: 'Asimi, Silver Tear',  # fmg
    3451: 'Smithing Master Hewg',  # fmg; name also on 6291 -- lowest id is canonical
    3665: 'Gatekeeper Gostoc',  # fmg
    3666: 'The Noble Goldmask',  # fmg
    3670: 'Pidia, Carian Servant',  # fmg
    3710: 'Primeval Sorcerer Azur',  # fmg
    3720: 'Primeval Sorcerer Lusat',  # fmg
    3730: 'Sorceress Sellen',  # fmg
    3950: 'Zorayas the Scout',  # fmg
    4110: 'Boc the Seamster',  # fmg
    4150: 'Basilisk',  # curated
    4490: 'Alexander, Warrior Jar',  # fmg
    4491: 'Jar-Bairn',  # fmg
    4604: 'Smithing Master Iji',  # fmg
    4630: 'Runebear',  # curated
    5280: 'Aging Untouchable',  # curated
    5330: 'St. Trina',  # fmg
    5710: 'Demi-Human Boc',  # fmg
    5910: 'Hornsent Grandam',  # fmg
    6091: 'Miriel, Pastor of Vows',  # fmg
    6210: 'Latenna the Albinauric',  # fmg; name also on 3170 -- lowest id is canonical
    6291: 'Smithing Master Hewg',  # fmg; name also on 3451 -- lowest id is canonical
}

#: chr_id -> 'fmg' (the game's own NpcName row) or 'curated' (a name this project already
#: published). Advisory: nothing branches on it, but a table that cannot say where a row
#: came from is one nobody can audit.
ENEMY_NAME_SOURCE = {
    2010: 'fmg',
    2030: 'fmg',
    2031: 'fmg',
    2050: 'fmg',
    2060: 'fmg',
    2110: 'fmg',
    2120: 'curated',
    2160: 'fmg',
    2170: 'fmg',
    2180: 'fmg',
    2500: 'fmg',
    3170: 'fmg',
    3200: 'fmg',
    3320: 'fmg',
    3451: 'fmg',
    3665: 'fmg',
    3666: 'fmg',
    3670: 'fmg',
    3710: 'fmg',
    3720: 'fmg',
    3730: 'fmg',
    3950: 'fmg',
    4110: 'fmg',
    4150: 'curated',
    4490: 'fmg',
    4491: 'fmg',
    4604: 'fmg',
    4630: 'curated',
    5280: 'curated',
    5330: 'fmg',
    5710: 'fmg',
    5910: 'fmg',
    6091: 'fmg',
    6210: 'fmg',
    6291: 'fmg',
}

#: The 6 model(s) whose name another model also carries. The resolver takes the LOWEST
#: model id; recorded here so the collision lives in the table and not only in the code.
ENEMY_NAME_COLLISIONS = {
    2030: ('Rennala, Queen of the Full Moon', [2031]),
    2031: ('Rennala, Queen of the Full Moon', [2030]),
    3170: ('Latenna the Albinauric', [6210]),
    3451: ('Smithing Master Hewg', [6291]),
    6210: ('Latenna the Albinauric', [3170]),
    6291: ('Smithing Master Hewg', [3451]),
}
