"""item_categories -- ONE player-facing taxonomy of the items this world puts in the pool.

WHY THIS EXISTS. Three different questions were being answered by three different splits:

  * `features/local_items.py` split by the ER FullID HIGH NIBBLE -- weapons / armor / talismans /
    goods / ashes. That is five buckets for 2084 items, and 933 of them are "goods", so the only
    control a player had over consumables, crafting materials, smithing stones, crystal tears,
    spirit ashes and spells was ONE switch that moved all six at once.
  * `features/filler_foreign.py` split by nothing at all: a percentage over a shuffled list of
    distinct filler NAMES. Which names it keeps is a coin toss, so the same setting means something
    different in every seed and a player cannot say "keep my crafting mats".
  * `features/filler_curation.py` has a real taxonomy -- throwables, pots, greases, stones, runes --
    but it is a RECIPE taxonomy: hand-listed rosters of the items worth INJECTING, ~120 names, and
    deliberately not a partition of the pool. Reusing it for locality would silently leave 800 goods
    uncovered.

So: a partition, derived from the game's own columns, that every category question can be asked
against. `GOODS_TYPE` (gen_data.py, EquipParamGoods.goodsType) is the column that makes it possible
-- before it existed there was no matt-free way to tell a crafting material from a smithing stone
from a throwing pot, because the id nibble calls all three "goods" and core calls all three "filler".

THE MOTIVATING CASE (boblerrr, Discord, 2026-08-08; LordChungle, Nexus, the same morning):
"crafting materials should be local, upgrade materials other than bell bearing can be local, same
with ghost gloveworts, every single consumable item should be local prob, small rune amounts should
not be sent out." Every clause of that is a category in the table below, and the last one is why
`rune_payout()` is here rather than a `runes` bucket alone -- "small" is a NUMBER the game already
publishes (SpEffectParam.soul, via shop_stock_data.RUNE_PAYOUT), so it does not need to be guessed.

🛑 THIS IS A PARTITION AND THE TEST ENFORCES IT. Every catalog item lands in exactly one category,
`other` included; nothing is dropped and nothing is double-counted. That property is the whole point
-- the moment a category can miss an item, "how much am I sending out?" stops being answerable, and
answering it is what the caller wanted.

🛑 A GOODS TYPE IS AN INVENTORY TAB, NOT A SEMANTIC CLASS. Type 1 holds the gate keys AND 96 crafting
cookbooks AND the bell bearings; type 0 holds throwing pots AND Golden Runes. Where we disagree with
the tab we say so here, by name, out loud -- `runes` is carved out of type 0 below, and that is a
judgement, not a column.

Matt-free: `ITEM_CATALOG` + `GOODS_TYPE` (param-derived, gen_data.py) and `RUNE_PAYOUT`
(EquipParamGoods.refId_default -> SpEffectParam.soul). No curated or location data.
"""
from typing import Dict, List, Optional

try:  # generated by gen_data.py -- {vanilla_item_name: ER FullID}
    from .item_ids import ITEM_CATALOG
except Exception:  # pre-regen / standalone import -> no real items exist
    ITEM_CATALOG = {}
try:  # generated by gen_data.py -- {goods_name: EquipParamGoods.goodsType}
    from .item_ids import GOODS_TYPE
except Exception:  # pre-regen item_ids.py -> every good collapses to "consumables" (see _goods_category)
    GOODS_TYPE = {}
try:  # generated by gen_data.py -- {goods row id: runes it pays out}
    from .shop_stock_data import RUNE_PAYOUT
except Exception:
    RUNE_PAYOUT = {}

# ---- the ER FullID high nibble: the classes that are their own category on sight ------------------
NIBBLE_CATEGORY: Dict[int, str] = {
    0x00000000: "weapons",
    0x10000000: "armor",
    0x20000000: "talismans",
    0x40000000: "goods",        # NOT a category -- subdivided by GOODS_TYPE below
    0x80000000: "ashes",        # ashes of WAR (the gems). Spirit ashes are goods; see spirit_ashes.
}
GOODS_NIBBLE = 0x40000000

# ---- EquipParamGoods.goodsType -> category. The legend lives in gen_data.py's GOODS_TYPE block. ----
# Types deliberately folded together: the four spell types (5/16/17/18) are one thing to a player,
# and both spirit-ash types (7 generic, 8 named) are one thing to a player.
GOODS_TYPE_CATEGORY: Dict[int, str] = {
    0: "consumables",           # minus the rune payouts -- carved out by name below
    1: "key_items",             # ...and cookbooks, and bell bearings. The tab, not the concept.
    2: "crafting",              # crafting MATERIALS (Aeonian Butterfly, Arteria Leaf, Beast Blood)
    3: "other",                 # remembrances
    5: "spells",
    7: "spirit_ashes",
    8: "spirit_ashes",
    9: "other",                 # Flask of Wondrous Physick
    10: "crystal_tears",
    11: "crafting",             # the vessels (Cracked Pot, Ritual Pot, Perfume Bottle)
    12: "other",                # paintings, map fragments, info items
    14: "upgrade_materials",    # Smithing Stone [1-8], Somber [1-9], Ghost Glovewort [1-9]
    15: "other",                # great runes
    16: "spells",
    17: "spells",
    18: "spells",
}

# `runes` is not a goodsType -- it is carved out of type 0 by the payout column (see _goods_category),
# so it has to be named here or it drops out of every set built from GOODS_TYPE_CATEGORY.
RUNES_CATEGORY = "runes"
# `cookbooks` is the SECOND carve-out, out of type 1, and unlike `runes` it is carved BY NAME. That
# is not a shortcut -- it is Alaric's ruling of 2026-07-28, already load-bearing in gen_data.py's
# `_KEY_ITEM_NAME_DROP`, and its reasoning applies verbatim here: "the param does not separate them,
# so this is OUR judgement about OUR pool and it should read like one rather than hide inside a
# filter." 96 of type 1's 220 members are crafting cookbooks; the rest are gate keys, bell bearings,
# whetblades and prayerbooks. The name mark is `_COOKBOOK_MARK` below and there is no decoy: no
# non-cookbook catalog name contains the word, and the test asserts that against the shipped
# KEY_ITEM_GOODS list rather than trusting it.
COOKBOOKS_CATEGORY = "cookbooks"
_COOKBOOK_MARK = "Cookbook"
_KEY_ITEM_GOODS_TYPE = 1
# THE THIRD AND FOURTH CARVE-OUTS, also out of type 1, and the first pair that splits on what an
# item DOES rather than what it is. All 48 bell bearings are mechanically identical -- hand one to
# the Twin Maiden Husks and stock appears -- but the stock is not the same kind of thing:
#
#   `upgrade_bells`  (13)  Smithing-Stone Miner's, Somberstone Miner's, (Ghost-)Glovewort Picker's.
#                          These ARE the upgrade economy. A seed without them has an amputated one,
#                          which is why features/presence_floor guarantees eight of them by name.
#   `merchant_bells` (35)  A dead merchant's own inventory, moved to the hub. Convenience.
#
# 🛑 IT IS A NAME CARVE AND THAT IS A JUDGEMENT, SAID OUT LOUD -- same as `runes` and `cookbooks`.
# The tempting oracle, `greenfield/bell_handins.tsv`, does NOT work: it is the Maidens' talk-ESD
# menu, it covers 23 of the 48 catalog bells, and its names do not join (`Kale's` vs `Kalé's`,
# `Nomadic Merchant's Bell Bearing [11]` absent from the catalog). Deriving from it would have
# filed Bone Peddler's and Herbalist's as upgrade bells. The CROSS-CHECK that does work is
# features/presence_floor's roster, picked by hand for exactly this reason and maintained
# separately: its 8 stone bells must all land in `upgrade_bells`, and the test asserts it.
#
# (Unrelated to features/merchant_bells.py, which grants the hand-in. Same subject, different job.)
UPGRADE_BELLS_CATEGORY = "upgrade_bells"
MERCHANT_BELLS_CATEGORY = "merchant_bells"
_BELL_MARK = "Bell Bearing"
# "Glovewort Picker's" deliberately catches "Ghost-Glovewort Picker's" too -- one mark, both ladders.
_UPGRADE_BELL_MARKS = ("Smithing-Stone Miner's", "Somberstone Miner's", "Glovewort Picker's")
# Every category key, sorted. `progressive` is not a catalog item -- it is the Progressive X upgrade
# items features/progressive.py registers -- and it has no FullID, so it is added by hand.
PROGRESSIVE_CATEGORY = "progressive"
CATEGORIES: List[str] = sorted(
    set(NIBBLE_CATEGORY.values()) - {"goods"}
    | set(GOODS_TYPE_CATEGORY.values())
    | {RUNES_CATEGORY, COOKBOOKS_CATEGORY, UPGRADE_BELLS_CATEGORY, MERCHANT_BELLS_CATEGORY,
       PROGRESSIVE_CATEGORY}
)


def rune_payout(name: str) -> Optional[int]:
    """The runes this item pays out when consumed, or None if it is not a rune. Param-derived
    (EquipParamGoods.refId_default -> SpEffectParam.soul). The ladder runs 200 (Golden Rune [1]) to
    80,000 (the DLC's largest), so "a small rune" is a number a player can actually name."""
    full = ITEM_CATALOG.get(name)
    if full is None or (full & 0xF0000000) != GOODS_NIBBLE:
        return None
    return RUNE_PAYOUT.get(full & 0x0FFFFFFF)


def _goods_category(name: str) -> str:
    """Category for a GOODS-nibble item.

    🛑 A MISSING TYPE MEANS `consumables`, AND THAT IS A DELIBERATE FAIL-SOFT. `GOODS_TYPE` is empty
    on a pre-regen item_ids.py; the alternative -- calling everything `other` -- would silently move
    the whole goods half of the pool OUT of the categories players select, so a `keep_local:
    [consumables]` yaml would stop holding anything back and never say why. Landing them in the
    largest goods category keeps the coarse behaviour and the count honest.
    """
    if rune_payout(name) is not None:
        # THE ONE JUDGEMENT CALL IN THIS FILE. Golden/Hero's/Lord's/Numen's/Shadow Realm Runes are
        # goodsType 0 -- the game files them with the throwing pots and the boluses. They are not
        # consumables in any sense a player means: they are the levelling currency, and "runes" is
        # the first thing anyone asks to control. Carved out by the payout column, not by name
        # matching "Rune" (which also hits Rune Arc, the Great Runes and Runebear-anything).
        return "runes"
    if (GOODS_TYPE.get(name) == _KEY_ITEM_GOODS_TYPE) and (_BELL_MARK in name):
        return (UPGRADE_BELLS_CATEGORY if any(m in name for m in _UPGRADE_BELL_MARKS)
                else MERCHANT_BELLS_CATEGORY)
    if (GOODS_TYPE.get(name) == _KEY_ITEM_GOODS_TYPE) and (_COOKBOOK_MARK in name):
        # THE SECOND JUDGEMENT CALL. Gated on the TYPE as well as the name so the mark can only ever
        # reclassify within the tab it was ruled about -- a future catalog item called "Cookbook
        # Grease" filed under consumables stays a consumable.
        return COOKBOOKS_CATEGORY
    return GOODS_TYPE_CATEGORY.get(GOODS_TYPE.get(name), "consumables")


# ---- THE GREAT RUNES: SEVEN, and keyed on the PARAM ROW, not the name ---------------------------
#
# 🛑 THE ONE DEFINITION. `core`, `features/leyndell_gate`, `features/natural_progression` and
# `features/legacy_key_gates` each used to carry their own `endswith("Great Rune")` over
# ITEM_CATALOG. Four copies of one predicate, and all four were WRONG in the same way:
# **"Great Rune of the Unborn" puts the words in the other order**, so a pure name-suffix match
# dropped it and every consumer counted six. That is the same species as joining `flag_lots` on a
# name -- a lexical test standing in for an identity.
#
# It went unnoticed because the miss looked like an absence. `core.GreatRunesRequired`'s docstring
# asserted the rune "is not an item you can be given" and "is not in the catalog at all"; by
# 2026-08-06 both were false. Rennala's flag 197 co-check (gen_data `_COCHECK_FLAGS`) put goods
# 10080 in the catalog AND on a location that day -- ap 7900004, "Raya Lucaria Academy :: Great Rune
# of the Unborn - Rennala [f197]" -- on Alaric's ruling that the GAME counts it toward the Leyndell
# wall: relief $Event(6905) maps 197 -> 177, inside the 170-179 possession band the gate counts
# (common $Event(730) -> flag 182; corrected 2026-08-22, clients#392).
# The item became a full citizen and the derivation never noticed.
#
# ⭐ ALARIC'S RULING, 2026-08-16: **there are seven Great Runes everywhere, and the Unborn rune is a
# full citizen.** Goal, capital wall, natural-progression count gate, legacy-key gate -- all seven.
#
# Keyed on the goods row id, which is the item's identity in the params and survives any FMG
# rename. `GREAT_RUNES_MISSING` is the loud half: an id that stops resolving is a data change we
# must see, so a test asserts it is empty rather than the set silently shrinking again.
GREAT_RUNE_GOODS_IDS: frozenset = frozenset({
    8148,   # Godrick's Great Rune
    8149,   # Radahn's Great Rune
    8150,   # Morgott's Great Rune
    8151,   # Rykard's Great Rune
    8152,   # Mohg's Great Rune
    8153,   # Malenia's Great Rune
    10080,  # Great Rune of the Unborn -- Rennala, flag 197, ap 7900004
})


def _resolve_great_runes() -> Dict[int, str]:
    """{goods id: catalog name} for the Great Runes present in this tree's ITEM_CATALOG."""
    out: Dict[int, str] = {}
    for name, full in ITEM_CATALOG.items():
        if (full & 0xF0000000) != GOODS_NIBBLE:
            continue
        gid = full & 0x0FFFFFFF
        if gid in GREAT_RUNE_GOODS_IDS:
            out[gid] = name
    return out


GREAT_RUNE_BY_GOODS: Dict[int, str] = _resolve_great_runes()
#: Sorted Great Rune item NAMES. Seven on a generated tree, empty pre-regen.
GREAT_RUNES: List[str] = sorted(GREAT_RUNE_BY_GOODS.values())
#: Goods ids we expect and did NOT find. Empty on a generated tree; pinned by the test suite rather
#: than asserted at import, because a player should never eat an ImportError over a data drift.
GREAT_RUNES_MISSING = tuple(sorted(GREAT_RUNE_GOODS_IDS - set(GREAT_RUNE_BY_GOODS))) if ITEM_CATALOG else ()


def category_of(name: str) -> str:
    """The one category `name` belongs to. Names outside ITEM_CATALOG are the Progressive X items
    (features/progressive.py registers them and they carry no FullID) -> `progressive`."""
    full = ITEM_CATALOG.get(name)
    if full is None:
        return PROGRESSIVE_CATEGORY
    if (full & 0xF0000000) == GOODS_NIBBLE:
        return _goods_category(name)
    return NIBBLE_CATEGORY.get(full & 0xF0000000, "other")


# UMBRELLA KEYS. `goods` was the only word for all of this before the split, and it is in players'
# yamls today (`exclude_local_item_only: [goods]`), so it has to keep meaning EXACTLY what it meant:
# every item with the goods nibble, no more and no less.
#
# 🛑 IT IS DERIVED FROM THE CATALOG, NOT TYPED OUT. The first version of this listed
# `set(GOODS_TYPE_CATEGORY.values())` -- which silently omitted `runes`, because runes are the one
# category carved out by payout rather than by type. A pre-split yaml saying `goods` then kept 31
# rune items local that it had always released, and the only reason that was caught before it
# shipped is that the pre-split test asserted over the NIBBLE (`all goods stay foreign-eligible`)
# instead of over the category list. Deriving the umbrella from the same nibble that test uses makes
# the omission unrepresentable: add a goods category tomorrow and the umbrella already covers it.
def _goods_categories() -> List[str]:
    cats = {category_of(n) for n, full in ITEM_CATALOG.items()
            if (full & 0xF0000000) == GOODS_NIBBLE}
    # Empty catalog (pre-regen) -> fall back to the static table so the option still verifies.
    return sorted(cats or (set(GOODS_TYPE_CATEGORY.values()) | {RUNES_CATEGORY}))


# 🛑 `key_items` IS THE SAME SITUATION AS `goods`, AND GETS THE SAME ANSWER. It is documented in the
# shipped release/EldenRing.yaml and named in the changelog, so it is in players' yamls today and it
# has to keep meaning EXACTLY what it meant: the whole inventory tab, cookbooks included. Splitting
# `cookbooks` out and leaving `key_items` narrowed would silently start sending 96 items abroad for
# every yaml that already says `keep_local: [key_items]`, with nothing to say so.
#
# So it is BOTH a category (the 124 that remain, which is what `category_of` answers) and an umbrella
# (all 220, which is what a yaml selecting it gets, because `expand` resolves umbrellas first). The
# consequence, stated rather than discovered: the narrowed 124 have no selector of their own. That is
# the right trade -- "key items" to a player means the tab, and `cookbooks` is how they peel the 96
# off it -- but it does mean `census()["key_items"]` (124) and `names_in(["key_items"])` (220) answer
# different questions on purpose. Both are pinned in test_gf_item_categories.
UMBRELLAS: Dict[str, List[str]] = {
    "goods": _goods_categories(),
    # Still the whole goodsType-1 tab, now four pieces instead of two. Same reason as before: it is
    # in players' yamls and may not quietly start releasing what it used to hold.
    "key_items": ["key_items", COOKBOOKS_CATEGORY, UPGRADE_BELLS_CATEGORY, MERCHANT_BELLS_CATEGORY],
    # Convenience over the split, so "all my bell bearings" stays one word for a player who does not
    # care which kind. NOT a compat key -- nothing shipped ever meant this -- purely additive.
    "bell_bearings": [UPGRADE_BELLS_CATEGORY, MERCHANT_BELLS_CATEGORY],
    "everything": list(CATEGORIES),
}
SELECTABLE: List[str] = sorted(set(CATEGORIES) | set(UMBRELLAS))


def expand(keys) -> List[str]:
    """Resolve a player's selection (categories and/or umbrella keys) to concrete category keys.
    Unknown keys are dropped rather than raised on -- the OptionSet's `valid_keys` is what rejects a
    typo, and it does it at yaml-verify time with a message naming the valid set."""
    out = set()
    for k in keys or ():
        k = str(k).strip()
        if k in UMBRELLAS:
            out.update(UMBRELLAS[k])
        elif k in CATEGORIES:
            out.add(k)
    return sorted(out)


def names_in(categories, extra_names=()) -> List[str]:
    """Every catalog item name whose category is in `categories`, plus any of `extra_names`
    (the progressive items, which are not in the catalog) that qualify. Sorted -- callers feed this
    to `local_items`, and a stable order keeps a seed's diagnostics diffable."""
    want = set(expand(categories))
    if not want:
        return []
    out = [n for n in ITEM_CATALOG if category_of(n) in want]
    if PROGRESSIVE_CATEGORY in want:
        out.extend(extra_names)
    return sorted(set(out))


def census() -> Dict[str, int]:
    """{category: how many distinct catalog names it holds}. The progressive items are not in the
    catalog, so `progressive` is absent here by construction."""
    out: Dict[str, int] = {}
    for n in ITEM_CATALOG:
        out[category_of(n)] = out.get(category_of(n), 0) + 1
    return out


# ---- CLASSIFICATION: the same partition, answering AP's useful/filler question --------------------
# WHY THIS IS HERE AND NOT IN core.py. `core._classify_full` used to answer "useful or filler?" from
# the FullID high nibble alone -- goods -> filler, everything else -> useful. That is a second,
# coarser partition of the same catalog, living in a different file, and it disagreed with this one
# in a way nobody could see: 203 spells, 79 spirit ashes and 37 crystal tears are gear to a player
# and carry the GOODS nibble, so AP's fill and every partner's tracker read them as junk. One
# taxonomy, asked two questions -- locality (`names_in`) and classification (here).
# ⭐ THAT DISAGREEMENT IS RESOLVED: the three categories were flipped to `useful` on 2026-08-12. The
# pin in test_gf_item_classification no longer asserts agreement with the retired nibble rule -- it
# asserts the difference is EXACTLY those three and nothing else has drifted since.
#
# 🛑 THIS TABLE IS THE POLICY AND IT IS WRITTEN OUT, NOT DERIVED. Deriving it from the nibble would
# reproduce today's answer forever and make the disagreement above unrepresentable -- which is the
# opposite of the point. It is pinned instead: `test_gf_item_classification` asserts this table
# agrees with the old nibble rule on every catalog name, so a flip is a DELIBERATE edit here that
# turns that test red and has to be argued for, and drift is impossible either way.
#
# 🛑 STRINGS, NOT `ItemClassification`. This module is AP-free on purpose (tools/ and the generators
# import it outside an Archipelago checkout); core maps these two keys onto the enum.
#
# 🛑🛑 TWO OF AP'S THREE CLASSES, AND THE THIRD IS NOT A CATEGORY PROPERTY. AP classifies an item
# progression / useful / filler (plus the `trap` label). This table mints only the last two, on
# purpose: PROGRESSION IS PER-NAME AND PER-WORLD -- whether Godrick's Great Rune gates anything
# depends on this seed's `goal`, and whether the Academy Glintstone Key does depends on
# features/legacy_key_gates. `core._class_for` decides that at item-creation time, above this table.
# A category can never answer it, because the same category holds both answers in the same seed.
#
# 🛑🛑 `progressive` IS NOT `progression`. The two words name unrelated things and sit one letter
# apart in the same file, so: PROGRESSIVE_CATEGORY is the bucket `category_of` returns for a name
# with no FullID, and the Progressive Flask / Stonesword Key / Smithing Bell / Somber Bell that give
# it its name are declared `useful` by features/progressive.py -- they gate nothing and never have.
# ItemClassification.progression is the AP class above, which no category grants. Reading the first
# as the second would promote every feature-minted name -- traps included -- into the fill's
# reachability constraints. `class_of` returns None for that bucket rather than risk it.
USEFUL = "useful"
FILLER = "filler"

CATEGORY_CLASS: Dict[str, str] = {
    # the four non-goods nibbles -- useful since the world shipped
    "weapons": USEFUL,
    "armor": USEFUL,
    "talismans": USEFUL,
    "ashes": USEFUL,
    # goods THAT ARE GEAR. Flipped 2026-08-12 (Alaric's call) -- these three are the disagreement
    # described above, and this is the line that ends it. A sorcery, a spirit ash and a crystal tear
    # are things a player equips, casts and drinks; the only reason they read as junk was that the
    # FullID nibble files them beside the crafting materials. 319 names, ~3.3% of a default pool's
    # copies. 🛑 THIS IS THE ONE ENTRY THAT MOVES SEEDS -- `useful` is the head of AP's
    # `restitempool`, so it is placed before any filler and the whole placement shifts.
    "spells": USEFUL,
    "spirit_ashes": USEFUL,
    "crystal_tears": USEFUL,
    # 🛑 `upgrade_materials` STAYS FILLER, and it is the closest call on this table. A Somber [9] is
    # not junk to a player -- but it is the economy features/filler_budget allocates BY THE HUNDRED
    # into the filler tail, and promoting the category would move that whole tail into the useful
    # tier. That is an economy change wearing a classification change's clothes. Argue it separately.
    "upgrade_materials": FILLER,
    # goods that are junk or currency by any reading, and stay filler
    "consumables": FILLER,
    "crafting": FILLER,
    # `cookbooks` was carved out of `key_items` and inherits its class UNCHANGED, so the split moved
    # no seed either. It is filler on its merits too: a cookbook unlocks a RECIPE, and the power is
    # in the material and the vessel, both of which are already filler above it.
    "cookbooks": FILLER,
    "runes": FILLER,
    # 🛑 THE TWO THE PARTITION CANNOT ANSWER. `key_items` is an inventory TAB holding the gate keys
    # AND 96 cookbooks AND the bell bearings; `other` holds remembrances, great runes, map fragments
    # and the Physick flask. A single class is wrong for both, so they keep the conservative one and
    # the promotions stay per-NAME in `core._class_for` (required great runes, Leyndell-gate runes,
    # legacy + natural keys -> progression). Do not "fix" these by flipping them wholesale.
    "key_items": FILLER,
    "other": FILLER,
    # ⭐ THE BELLS, AND THE WHOLE POINT OF SPLITTING THEM. An upgrade bell is the smithing economy
    # arriving in one item -- Alaric, 2026-08-12: "upgrade_materials filler is fine as long as we
    # keep the stone bell bearings useful". It was NOT true when he said it: the bells sat in
    # `key_items` and classed filler, and only the copies features/presence_floor INJECTS were
    # promoted, so a naturally-placed Somberstone [4] was junk. This is the line that makes it true.
    # A merchant bell moves a dead merchant's shelf to the hub -- convenient, not power.
    "upgrade_bells": USEFUL,
    "merchant_bells": FILLER,
    # PROGRESSIVE_CATEGORY is deliberately absent -- see class_of().
}


# ---- THE PERMANENT POWER-UPS: a per-NAME promotion, because the category cannot carry it ---------
# A Golden Seed is consumed once and raises your flask count for the rest of the run. It is not junk
# and a partner receiving one has been given something. But it cannot be promoted the way `spells`
# and `crystal_tears` were, because it is not in a category of its own: `GOODS_TYPE` files Golden
# Seed, Sacred Tear, Scadutree Fragment and Revered Spirit Ash under **type 14 -- the same type as
# `Smithing Stone [1]`** -- so they land in `upgrade_materials`, which the table above deliberately
# keeps FILLER ("an economy change wearing a classification change's clothes"). Flipping the category
# would move features/filler_budget's entire hundreds-strong smithing tail into the useful tier.
#
# So this is the third name-based carve-out in this file, and it is the same species as the other two
# (`runes` out of type 0 by payout, `cookbooks` out of type 1 by mark): the param does not separate
# them, so it is OUR judgement about OUR pool and it should read like one rather than hide inside a
# filter. Four names, listed, each with the reason it is not a crafting material.
#
# 🛑 IT GOES HERE AND NOT IN `core._class_for`, even though that is where per-name promotions
# normally live. The consumers must AGREE: features/filler_foreign builds its candidate list from
# `class_of` and would otherwise keep calling a Golden Seed filler while core called it useful, and
# a low `filler_foreign_pct` would then hold back an item the classification says should travel.
# One taxonomy, asked once -- which is the whole reason `class_of` replaced the private nibble test.
USEFUL_GOODS = frozenset({
    "Golden Seed",              # +1 flask charge, permanent
    "Sacred Tear",              # +1 flask potency, permanent
    "Scadutree Fragment",       # the DLC's damage/defence ladder
    "Revered Spirit Ash",       # the DLC's spirit-ash ladder
})


def class_of(name: str) -> Optional[str]:
    """`USEFUL` or `FILLER` for a catalog item, or None if this taxonomy has no opinion.

    None means the caller owns the answer, and there is exactly one such case: a name outside
    `ITEM_CATALOG`. `category_of` folds all of those into `progressive`, which is NOT the set of
    Progressive X items -- it is every feature-minted name, so it also holds the region Locks and
    boss keys (progression), the traps and the FILLER sentinel (filler), and scadu_supply's
    fragment (useful). Four classes in one bucket; the features DECLARE those in their `ITEMS` and
    that declaration must win. Returning None rather than a class is what keeps this module from
    silently overruling them (`features/keep_out_of_shops.py` documents the same trap for locality).
    """
    if name not in ITEM_CATALOG:
        return None
    if name in USEFUL_GOODS:        # see USEFUL_GOODS -- the category cannot answer for these four
        return USEFUL
    return CATEGORY_CLASS.get(category_of(name), FILLER)
