"""item_categories -- ONE player-facing taxonomy of the items this world puts in the pool.

WHY THIS EXISTS. Three different questions were being answered by three different splits:

  * `features/local_items.py` split by the ER FullID HIGH NIBBLE -- weapons / armor / talismans /
    goods / ashes. That is five buckets for 2084 items, and 933 of them are "goods", so the only
    control a player had over consumables, crafting materials, smithing stones, crystal tears,
    spirit ashes and spells was ONE switch that moved all six at once.
  * `features/filler_foreign.py` split by nothing at all: a percentage over a shuffled list of
    distinct filler NAMES. Which names it keeps is a coin toss, so the same setting means something
    different in every seed and a player cannot say "keep my crafting mats".
  * `features/filler_curation.py` has a real taxonomy -- throwables, pots, greases, stones, runes --
    but it is a RECIPE taxonomy: hand-listed rosters of the items worth INJECTING, ~120 names, and
    deliberately not a partition of the pool. Reusing it for locality would silently leave 800 goods
    uncovered.

So: a partition, derived from the game's own columns, that every category question can be asked
against. `GOODS_TYPE` (gen_data.py, EquipParamGoods.goodsType) is the column that makes it possible
-- before it existed there was no matt-free way to tell a crafting material from a smithing stone
from a throwing pot, because the id nibble calls all three "goods" and core calls all three "filler".

THE MOTIVATING CASE (boblerrr, Discord, 2026-08-08; LordChungle, Nexus, the same morning):
"crafting materials should be local, upgrade materials other than bell bearing can be local, same
with ghost gloveworts, every single consumable item should be local prob, small rune amounts should
not be sent out." Every clause of that is a category in the table below, and the last one is why
`rune_payout()` is here rather than a `runes` bucket alone -- "small" is a NUMBER the game already
publishes (SpEffectParam.soul, via shop_stock_data.RUNE_PAYOUT), so it does not need to be guessed.

🛑 THIS IS A PARTITION AND THE TEST ENFORCES IT. Every catalog item lands in exactly one category,
`other` included; nothing is dropped and nothing is double-counted. That property is the whole point
-- the moment a category can miss an item, "how much am I sending out?" stops being answerable, and
answering it is what the caller wanted.

🛑 A GOODS TYPE IS AN INVENTORY TAB, NOT A SEMANTIC CLASS. Type 1 holds the gate keys AND 96 crafting
cookbooks AND the bell bearings; type 0 holds throwing pots AND Golden Runes. Where we disagree with
the tab we say so here, by name, out loud -- `runes` is carved out of type 0 below, and that is a
judgement, not a column.

Matt-free: `ITEM_CATALOG` + `GOODS_TYPE` (param-derived, gen_data.py) and `RUNE_PAYOUT`
(EquipParamGoods.refId_default -> SpEffectParam.soul). No curated or location data.
"""
from typing import Dict, List, Optional

try:  # generated by gen_data.py -- {vanilla_item_name: ER FullID}
    from .item_ids import ITEM_CATALOG
except Exception:  # pre-regen / standalone import -> no real items exist
    ITEM_CATALOG = {}
try:  # generated by gen_data.py -- {goods_name: EquipParamGoods.goodsType}
    from .item_ids import GOODS_TYPE
except Exception:  # pre-regen item_ids.py -> every good collapses to "consumables" (see _goods_category)
    GOODS_TYPE = {}
try:  # generated by gen_data.py -- {goods row id: runes it pays out}
    from .shop_stock_data import RUNE_PAYOUT
except Exception:
    RUNE_PAYOUT = {}

# ---- the ER FullID high nibble: the classes that are their own category on sight ------------------
NIBBLE_CATEGORY: Dict[int, str] = {
    0x00000000: "weapons",
    0x10000000: "armor",
    0x20000000: "talismans",
    0x40000000: "goods",        # NOT a category -- subdivided by GOODS_TYPE below
    0x80000000: "ashes",        # ashes of WAR (the gems). Spirit ashes are goods; see spirit_ashes.
}
GOODS_NIBBLE = 0x40000000

# ---- EquipParamGoods.goodsType -> category. The legend lives in gen_data.py's GOODS_TYPE block. ----
# Types deliberately folded together: the four spell types (5/16/17/18) are one thing to a player,
# and both spirit-ash types (7 generic, 8 named) are one thing to a player.
GOODS_TYPE_CATEGORY: Dict[int, str] = {
    0: "consumables",           # minus the rune payouts -- carved out by name below
    1: "key_items",             # ...and cookbooks, and bell bearings. The tab, not the concept.
    2: "crafting",              # crafting MATERIALS (Aeonian Butterfly, Arteria Leaf, Beast Blood)
    3: "other",                 # remembrances
    5: "spells",
    7: "spirit_ashes",
    8: "spirit_ashes",
    9: "other",                 # Flask of Wondrous Physick
    10: "crystal_tears",
    11: "crafting",             # the vessels (Cracked Pot, Ritual Pot, Perfume Bottle)
    12: "other",                # paintings, map fragments, info items
    14: "upgrade_materials",    # Smithing Stone [1-8], Somber [1-9], Ghost Glovewort [1-9]
    15: "other",                # great runes
    16: "spells",
    17: "spells",
    18: "spells",
}

# THE PERMANENT POWER-UPS, carved out of the goods for CLASSIFICATION rather than for a category.
# They keep their category (`upgrade_materials`) -- a player asking to keep_local their upgrade
# materials means these too -- but core classifies them `useful` instead of `filler`, because they
# are consumed once and raise a stat for the rest of the run. That makes them the one place where
# "which inventory tab is this in" and "how much does finding it matter" genuinely disagree.
#
# It lives here rather than in core because features may not import ..core (circular), and
# features/filler_foreign has to subtract exactly this set from its nibble-derived filler list or
# the two would call the same item different things. core imports it from here.
USEFUL_GOODS = frozenset({
    "Golden Seed",              # +1 flask charge, permanent
    "Sacred Tear",              # +1 flask potency, permanent
    "Scadutree Fragment",       # the DLC's damage/defence ladder
    "Revered Spirit Ash",       # the DLC's spirit-ash ladder
})

# `runes` is not a goodsType -- it is carved out of type 0 by the payout column (see _goods_category),
# so it has to be named here or it drops out of every set built from GOODS_TYPE_CATEGORY.
RUNES_CATEGORY = "runes"
# Every category key, sorted. `progressive` is not a catalog item -- it is the Progressive X upgrade
# items features/progressive.py registers -- and it has no FullID, so it is added by hand.
PROGRESSIVE_CATEGORY = "progressive"
CATEGORIES: List[str] = sorted(
    set(NIBBLE_CATEGORY.values()) - {"goods"}
    | set(GOODS_TYPE_CATEGORY.values())
    | {RUNES_CATEGORY, PROGRESSIVE_CATEGORY}
)


def rune_payout(name: str) -> Optional[int]:
    """The runes this item pays out when consumed, or None if it is not a rune. Param-derived
    (EquipParamGoods.refId_default -> SpEffectParam.soul). The ladder runs 200 (Golden Rune [1]) to
    80,000 (the DLC's largest), so "a small rune" is a number a player can actually name."""
    full = ITEM_CATALOG.get(name)
    if full is None or (full & 0xF0000000) != GOODS_NIBBLE:
        return None
    return RUNE_PAYOUT.get(full & 0x0FFFFFFF)


def _goods_category(name: str) -> str:
    """Category for a GOODS-nibble item.

    🛑 A MISSING TYPE MEANS `consumables`, AND THAT IS A DELIBERATE FAIL-SOFT. `GOODS_TYPE` is empty
    on a pre-regen item_ids.py; the alternative -- calling everything `other` -- would silently move
    the whole goods half of the pool OUT of the categories players select, so a `keep_local:
    [consumables]` yaml would stop holding anything back and never say why. Landing them in the
    largest goods category keeps the coarse behaviour and the count honest.
    """
    if rune_payout(name) is not None:
        # THE ONE JUDGEMENT CALL IN THIS FILE. Golden/Hero's/Lord's/Numen's/Shadow Realm Runes are
        # goodsType 0 -- the game files them with the throwing pots and the boluses. They are not
        # consumables in any sense a player means: they are the levelling currency, and "runes" is
        # the first thing anyone asks to control. Carved out by the payout column, not by name
        # matching "Rune" (which also hits Rune Arc, the Great Runes and Runebear-anything).
        return "runes"
    return GOODS_TYPE_CATEGORY.get(GOODS_TYPE.get(name), "consumables")


def category_of(name: str) -> str:
    """The one category `name` belongs to. Names outside ITEM_CATALOG are the Progressive X items
    (features/progressive.py registers them and they carry no FullID) -> `progressive`."""
    full = ITEM_CATALOG.get(name)
    if full is None:
        return PROGRESSIVE_CATEGORY
    if (full & 0xF0000000) == GOODS_NIBBLE:
        return _goods_category(name)
    return NIBBLE_CATEGORY.get(full & 0xF0000000, "other")


# UMBRELLA KEYS. `goods` was the only word for all of this before the split, and it is in players'
# yamls today (`exclude_local_item_only: [goods]`), so it has to keep meaning EXACTLY what it meant:
# every item with the goods nibble, no more and no less.
#
# 🛑 IT IS DERIVED FROM THE CATALOG, NOT TYPED OUT. The first version of this listed
# `set(GOODS_TYPE_CATEGORY.values())` -- which silently omitted `runes`, because runes are the one
# category carved out by payout rather than by type. A pre-split yaml saying `goods` then kept 31
# rune items local that it had always released, and the only reason that was caught before it
# shipped is that the pre-split test asserted over the NIBBLE (`all goods stay foreign-eligible`)
# instead of over the category list. Deriving the umbrella from the same nibble that test uses makes
# the omission unrepresentable: add a goods category tomorrow and the umbrella already covers it.
def _goods_categories() -> List[str]:
    cats = {category_of(n) for n, full in ITEM_CATALOG.items()
            if (full & 0xF0000000) == GOODS_NIBBLE}
    # Empty catalog (pre-regen) -> fall back to the static table so the option still verifies.
    return sorted(cats or (set(GOODS_TYPE_CATEGORY.values()) | {RUNES_CATEGORY}))


UMBRELLAS: Dict[str, List[str]] = {
    "goods": _goods_categories(),
    "everything": list(CATEGORIES),
}
SELECTABLE: List[str] = sorted(set(CATEGORIES) | set(UMBRELLAS))


def expand(keys) -> List[str]:
    """Resolve a player's selection (categories and/or umbrella keys) to concrete category keys.
    Unknown keys are dropped rather than raised on -- the OptionSet's `valid_keys` is what rejects a
    typo, and it does it at yaml-verify time with a message naming the valid set."""
    out = set()
    for k in keys or ():
        k = str(k).strip()
        if k in UMBRELLAS:
            out.update(UMBRELLAS[k])
        elif k in CATEGORIES:
            out.add(k)
    return sorted(out)


def names_in(categories, extra_names=()) -> List[str]:
    """Every catalog item name whose category is in `categories`, plus any of `extra_names`
    (the progressive items, which are not in the catalog) that qualify. Sorted -- callers feed this
    to `local_items`, and a stable order keeps a seed's diagnostics diffable."""
    want = set(expand(categories))
    if not want:
        return []
    out = [n for n in ITEM_CATALOG if category_of(n) in want]
    if PROGRESSIVE_CATEGORY in want:
        out.extend(extra_names)
    return sorted(set(out))


def census() -> Dict[str, int]:
    """{category: how many distinct catalog names it holds}. The progressive items are not in the
    catalog, so `progressive` is absent here by construction."""
    out: Dict[str, int] = {}
    for n in ITEM_CATALOG:
        out[category_of(n)] = out.get(category_of(n), 0) + 1
    return out
