"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Per-region warp-grace open flags for the Phase 0 boot
contract; derived from grace anchors (matt-free). PENDING = DLC sub-area to resolve in
the region audit (SPEC-PARITY.md 14.4); client treats an absent open flag as unlocked."""
REGION_OPEN_FLAGS = {
    'Abyssal': 76860,
    'Ainsel River': 71211,
    'Altus': 76301,
    'Ancient Ruins': 76940,
    'Belurat': 72001,
    'Caelid': 73207,
    'Cerulean': 76831,
    'Consecrated Snowfield': 76550,
    'Deeproot Depths': 71231,
    'Enir Ilim': 72012,
    'Ensis': 76821,
    'Farum Azula': 71303,
    'Gravesite': 76800,
    'Haligtree': 71501,
    'Jagged Peak': 76840,
    'Leyndell': 76980,
    'Limgrave': 73100,
    'Liurnia': 73202,
    'Mohgwyn': 71251,
    'Mountaintops of the Giants': 73017,
    'Mt. Gelmir': 76350,
    'Rauh Base': 76912,
    'Raya Lucaria Academy': 76981,
    'Scadu Altus': 76900,
    'Shadow Keep': 76935,
    'Siofra River': 71222,
    'Stormveil': 71003,
    'Weeping': 73102,
    'Ashen Capital': 71123,
}

REGION_OPEN_PENDING = [
]

_GEN_STAMP = {'inputs_hash': 'sha256:6e786569526a11b77a7e69cb6725a437e5be2879d6b128012334be2e8f468d4d', 'module': 'region_open_flags.py', 'body_sha256': 'sha256:7c2c446ea7da7d4b28ebee77057c34446d7c718c9339a74f69df58eec66fb5b5'}
