"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py).
Region -> play_region ids (kick-watch geometry), the inverse of
region_groups.PLAY_REGION_GROUPS -- the buckets MEASURED from PlayRegionParam, NOT the
BonfireWarpParam warp-menu ids that REGION_GROUPS is keyed by (they are different numbers
for the same places; conflating them left the kick permissive on most of the map). Minus
the kick-excluded buckets (Roundtable HUB 11100; the intro/tutorial spawn buckets 18000
and 10010 -- see region_groups.KICK_EXCLUDED_PLAY_IDS). Consumed by
features/area_locks.py (areaLockFlags) and baked into the client (tools/gen_region_locks.py)."""
REGION_PLAY_IDS = {
    'Abyssal': [68600],
    'Ainsel River': [12010],
    'Altus': [30070, 30080, 30100, 30120, 30130, 31180, 31190, 32040, 32050, 34120, 34140, 63000, 63010],
    'Ancient Ruins': [69400, 69410],
    'Ashen Capital': [11050, 19000],
    'Belurat': [20000],
    'Caelid': [30140, 30150, 30160, 31100, 31110, 31200, 31210, 32070, 32080, 34130, 64000, 64010, 64020],
    'Cerulean': [22000, 41020, 68300, 68400],
    'Deeproot Depths': [12030],
    'Enir Ilim': [20010],
    'Ensis': [68200],
    'Farum Azula': [13000],
    'Gravesite': [40000, 41000, 42000, 43000, 43010, 68000, 68100],
    'Haligtree': [15000],
    'Jagged Peak': [68410, 68500],
    'Leyndell': [11000],
    'Limgrave': [30020, 30040, 30110, 31000, 31030, 31150, 31170, 32010, 34100, 61000, 61010],
    'Liurnia': [30030, 30050, 30060, 31040, 31050, 31060, 32020, 34110, 39200, 62000, 62010, 62020],
    'Mohgwyn': [12050],
    'Mountaintops of the Giants': [30170, 30180, 30190, 30200, 31120, 31220, 32110, 65000, 65010, 65020, 65030],
    'Mt. Gelmir': [16000, 30090, 31070, 31090, 63020],
    'Rauh Base': [40010, 42030, 69010],
    'Raya Lucaria Academy': [14000],
    'Scadu Altus': [40020, 41010, 42020, 69000, 69020, 69030],
    'Sewer': [35000],
    'Shadow Keep': [21000, 21010, 21020, 69300],
    'Siofra River': [12020, 12070],
    'Stormveil': [10000],
    'Weeping': [30000, 30010, 31010, 31020, 32000, 61020],
}

# Regions whose play_region buckets are NOT measured yet, so their locks CANNOT be
# enforced. core._eligible_regions drops them from the seed's region pool (and says so):
# shipping a lock that does nothing is the bug the measured table exists to end.
REGIONS_PENDING_BUCKET = frozenset([])

_GEN_STAMP = {'inputs_hash': 'sha256:c08706f6faa8734985573ddaadfbcb9dbafe6f2c4cad1a481d5fa468c43fc2d1', 'module': 'region_play_ids.py', 'body_sha256': 'sha256:69957cdcac53e19832cdaae8388d66949729cecd137b6c2d768e1138a5d6ca80'}
