"""AUTO-GENERATED by greenfield/gen_data.py -- DO NOT EDIT (regenerate: python greenfield/gen_data.py; see gen-greenfield.ps1). Per-region warp-grace open flags for the Phase 0 boot
contract; derived from grace anchors (matt-free). PENDING = DLC sub-area to resolve in
the region audit (SPEC-PARITY.md 14.4); client treats an absent open flag as unlocked."""
REGION_OPEN_FLAGS = {
    'Abyssal': 76860,
    'Ainsel River': 71211,
    'Altus': 73204,
    'Ancient Ruins': 76940,
    'Belurat': 72001,
    'Caelid': 73207,
    'Cerulean': 76831,
    'Deeproot Depths': 71231,
    'Enir Ilim': 72012,
    'Ensis': 76821,
    'Farum Azula': 71303,
    'Gravesite': 76800,
    'Haligtree': 71501,
    'Jagged Peak': 76840,
    'Leyndell': 76980,
    'Limgrave': 73100,
    'Liurnia': 73202,
    'Mohgwyn': 71251,
    'Mountaintops of the Giants': 73017,
    'Mt. Gelmir': 76350,
    'Rauh Base': 76912,
    'Raya Lucaria Academy': 76981,
    'Scadu Altus': 76900,
    'Sewer': 76982,
    'Shadow Keep': 76935,
    'Siofra River': 71222,
    'Stormveil': 71003,
    'Weeping': 73102,
    'Ashen Capital': 71122,
}

REGION_OPEN_PENDING = [
]

_GEN_STAMP = {'inputs_hash': 'sha256:c08706f6faa8734985573ddaadfbcb9dbafe6f2c4cad1a481d5fa468c43fc2d1', 'module': 'region_open_flags.py', 'body_sha256': 'sha256:e578ed7958e74bafc78ef41eefe5a5a44836f859c231d2ac240168708ce81687'}
